server:
    error:
        include-message: always
        include-binding-errors: always
    port: 4449

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/project_panther_poc
        username: postgres
        password: start123$
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show_sql: true

